version: 2

sources:
  - name: raw
    database: curious-mender-475710-a7
    schema: gz_raw_data

    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: order_id
            description: order identification
          - name: pdt_id
            description: product identification
        tests:
          - unique:
              column_name: "(order_id ||'-'|| date_date)"

      - name: product
        identifier: raw_gz_product
        description: products and its pricing of Greenweez
        columns:
          - name: product_id
            description: product identification
        tests:
          - unique
          - not_null

      - name: ship
        identifier: raw_gz_ship
        description: shipping cost of orders on Greenweez
        columns:
          - name: order_id
            description: order identification
        tests:
          - unique
          - not_null
